#! /bin/sh

# bootstrap is a shell script that generates all the Autotools scripts.
# Copyright (C) 2002, 2003  Billy Biggs
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

# If you are not compiling with GCC, you should set $CC_NOTGCC to 1.
test -z "${CC_NOTGCC}" || CC_NOTGCC='--include-deps'

# We will attempt to auto-detect the existance of the correct
# GNU Autotools binaries.  We will prefer specific versions over others.
# To manually override, set the appropriate $AUTOCONF, $AUTOHEADER,
# $AUTOMAKE, $ACLOCAL, and $LIBTOOLIZE environment variables

test -x "$AUTOCONF" ||
  AUTOCONF=`type -p autoconf2.50` ||
    AUTOCONF=`type -p autoconf` ||
      {
        echo `basename $0`: cannot find GNU Autoconf 1>&2 && 
          exit 1;
      }

test -x "$AUTOHEADER" ||
  AUTOHEADER="autoheader`echo "$AUTOCONF" | sed 's/.*autoconf//'`" &&
    AUTOHEADER=`type -p "$AUTOHEADER"` ||
      {
        echo `basename $0`: GNU Autoconf installed improperly 1>&2 && 
          exit 2;
      }

test -x "$AUTOMAKE" ||
  AUTOMAKE=`type -p automake-1.7` ||
    AUTOMAKE=`type -p automake-1.6` ||
      AUTOMAKE=`type -p automake` ||
        {
          echo `basename $0`: cannot find GNU Automake 1>&2 &&
            exit 3;
        }

test -x "$ACLOCAL" ||
  ACLOCAL="aclocal`echo "$AUTOMAKE" | sed 's/.*automake//'`" &&
    ACLOCAL=`type -p "$ACLOCAL"` ||
      {
        echo `basename $0`: GNU Automake installed improperly 1>&2 && 
          exit 4;
      }

test -x "$LIBTOOLIZE" ||
  LIBTOOLIZE=`type -p libtoolize` ||
    {
      echo `basename $0`: cannot find GNU libtool 1>&2 &&
        exit 5;
    }

${ACLOCAL} &&
  ${LIBTOOLIZE} --force --copy &&
    ${AUTOHEADER} &&
      ${AUTOMAKE} --add-missing --copy ${CC_NOTGCC} &&
        ${AUTOCONF} &&
          rm -f config.cache
