#!/bin/sh 
# config script for tvtime

# Source debconf library.
. /usr/share/debconf/confmodule

db_input high tvtime/setuid || true
db_input medium tvtime/processpriority || true
db_input medium tvtime/v4ldevice || true
db_input medium tvtime/vbidevice || true
db_input medium tvtime/norm || true
db_go

db_get tvtime/norm
case "$RET" in
    NTSC|PAL-M|PAL-Nc)
        db_input medium tvtime/frequencies-ntsc || true
        ;;
    NTSC-JP)
        db_input medium tvtime/frequencies-jp || true
        ;;
    *)
        db_input medium tvtime/frequencies-pal || true
esac
db_go

exit 0
