#! /bin/sh
# postinst script for tvtime

set -e

action=$1

if [ "$action" = "configure" ]; then
    # Source debconf library.
    . /usr/share/debconf/confmodule

    if [ ! -e /etc/tvtime/tvtime.xml ]; then
        gunzip -c /usr/share/doc/tvtime/examples/default.tvtime.xml.gz > /etc/tvtime/tvtime.xml
    fi

    db_get tvtime/norm
    tvtime-configure --configfile=/etc/tvtime/tvtime.xml --norm=$RET
    case "$RET" in
        NTSC|PAL-M|PAL-Nc)
            db_get tvtime/frequencies-ntsc
            case "$RET" in
                Cable) tvtime-configure --configfile=/etc/tvtime/tvtime.xml --frequencies=us-cable ;;
                Broadcast) tvtime-configure --configfile=/etc/tvtime/tvtime.xml --frequencies=us-broadcast ;;
                *) tvtime-configure --configfile=/etc/tvtime/tvtime.xml --frequencies=us-cable100 ;;
            esac
            ;;
        NTSC-JP)
            db_get tvtime/frequencies-jp
            case "$RET" in
                Cable) tvtime-configure --configfile=/etc/tvtime/tvtime.xml --frequencies=japan-cable ;;
                *) tvtime-configure --configfile=/etc/tvtime/tvtime.xml --frequencies=japan-broadcast ;;
            esac
            ;;
        *)
            db_get tvtime/frequencies-pal
            case "$RET" in
                Europe) tvtime-configure --configfile=/etc/tvtime/tvtime.xml --frequencies=europe ;;
                France) tvtime-configure --configfile=/etc/tvtime/tvtime.xml --frequencies=france ;;
                Russia) tvtime-configure --configfile=/etc/tvtime/tvtime.xml --frequencies=russia ;;
                Australia) tvtime-configure --configfile=/etc/tvtime/tvtime.xml --frequencies=australia ;;
                "New Zealand") tvtime-configure --configfile=/etc/tvtime/tvtime.xml --frequencies=newzealand ;;
                "China Broadcast") tvtime-configure --configfile=/etc/tvtime/tvtime.xml --frequencies=china-broadcast ;;
                "Australia Optus cable") tvtime-configure --configfile=/etc/tvtime/tvtime.xml --frequencies=australia-optus ;;
                *) tvtime-configure --configfile=/etc/tvtime/tvtime.xml --frequencies=custom ;;
            esac
            ;;
    esac

    db_get tvtime/v4ldevice
    tvtime-configure --configfile=/etc/tvtime/tvtime.xml --device=$RET

    db_get tvtime/vbidevice
    tvtime-configure --configfile=/etc/tvtime/tvtime.xml --vbidevice=$RET

    db_get tvtime/processpriority
    tvtime-configure --configfile=/etc/tvtime/tvtime.xml --priority=$RET

    db_get tvtime/setuid
    if [ -x /usr/bin/tvtime -a "$RET" = "false" ] ; then
        chmod u-s /usr/bin/tvtime
    else
        chmod u+s /usr/bin/tvtime
    fi

    # Create the video devices if they don't exist.
    if [ ! -c '/dev/video0' ]; then
        echo "Creating video devices in \`/dev'."
        ( cd /dev; ./MAKEDEV video )
    fi
fi

exit 0
