#! /bin/sh
# postinst script for tvtime

set -e

action=$1

CONFIGFILE=/etc/tvtime/tvtime.xml

if [ "$action" = "configure" ]; then
    # Source debconf library.
    . /usr/share/debconf/confmodule

    # Handle the setuid bit.
    db_get tvtime/setuid
    if [ -x /usr/bin/tvtime -a "$RET" = "false" ] ; then
        if [ ! -x /usr/sbin/dpkg-statoverride ] || \
           ! /usr/sbin/dpkg-statoverride --list /usr/bin/tvtime >/dev/null; then
            chmod u=rwx,go=rx /usr/bin/tvtime
	    chown root:root /usr/bin/tvtime
        fi
    else
        if [ ! -x /usr/sbin/dpkg-statoverride ] || \
           ! /usr/sbin/dpkg-statoverride --list /usr/bin/tvtime >/dev/null; then
            chmod u=rwxs,go=rx /usr/bin/tvtime
	    chown root:root /usr/bin/tvtime
        fi
    fi

    # Try to set the /var/run/tvtime directory to video group
    if [ -d /var/run/tvtime ] ; then
        if [ ! -x /usr/sbin/dpkg-statoverride ] || \
           ! /usr/sbin/dpkg-statoverride --list /var/run/tvtime >/dev/null; then
	    chmod ug=rwx,o=rxt /var/run/tvtime
            chown root:video /var/run/tvtime
        fi
    fi

    db_get tvtime/norm
    NORM=$RET
    case "$NORM" in
        NTSC|PAL-M|PAL-Nc)
            db_get tvtime/frequencies-ntsc
            case "$RET" in
                Cable) FREQTABLE=us-cable ;;
                Broadcast) FREQTABLE=us-broadcast ;;
                *) FREQTABLE=us-cable100 ;;
            esac
            ;;
        NTSC-JP)
            db_get tvtime/frequencies-jp
            case "$RET" in
                Cable) FREQTABLE=japan-cable ;;
                *) FREQTABLE=japan-broadcast ;;
            esac
            ;;
        *)
            db_get tvtime/frequencies-pal
            case "$RET" in
                Europe) FREQTABLE=europe ;;
                France) FREQTABLE=france ;;
                Russia) FREQTABLE=russia ;;
                Australia) FREQTABLE=australia ;;
                "New Zealand") FREQTABLE=newzealand ;;
                "China Broadcast") FREQTABLE=china-broadcast ;;
                "Australia Optus cable") FREQTABLE=australia-optus ;;
                *) FREQTABLE=custom ;;
            esac
            ;;
    esac

    db_get tvtime/v4ldevice
    V4LDEV=$RET
    db_get tvtime/vbidevice
    VBIDEV=$RET
    db_get tvtime/processpriority
    PRI=$RET

    # Start with the new default config file.
    gunzip -c /usr/share/doc/tvtime/examples/default.tvtime.xml.gz > $CONFIGFILE.new

    # Configure tvtime.
    tvtime-configure --configfile=$CONFIGFILE.new --norm=$NORM \
	--frequencies=$FREQTABLE --device=$V4LDEV --vbidevice=$VBIDEV \
	--priority=$PRI

    # Now run ucf on our new config file.
    db_stop

    ucf $CONFIGFILE.new $CONFIGFILE </dev/tty
    rm -f $CONFIGFILE.new

    # Create the video devices if they don't exist.
    if [ ! -c '/dev/video0' ]; then
        echo "Creating video devices in \`/dev'."
        ( cd /dev; ./MAKEDEV video )
    fi
fi

#DEBHELPER#

exit 0
