#!/bin/bash
# Downloads tvtime from CVS into the current working
# directory and packages it into RPM format
#
# by Paul Jara
# 2002 12 18

PROJNAME="tvtime"
export PROJVER="0.9.7" # Not really but RPM wants a version so use current version + 1

echo ""
echo ""
echo ""
echo "************************************************"
echo "When prompted for a password, simply press Enter"
echo "************************************************"
echo ""
echo ""
echo ""
cvs -z3 -d:pserver:anonymous@cvs.tvtime.sourceforge.net:/cvsroot/tvtime login
cvs -z3 -d:pserver:anonymous@cvs.tvtime.sourceforge.net:/cvsroot/tvtime co tvtime
pushd $PROJNAME
sh autogen.sh
popd
mv $PROJNAME $PROJNAME-$PROJVER
tar -cf $PROJNAME-$PROJVER.tar $PROJNAME-$PROJVER
gzip $PROJNAME-$PROJVER.tar
cp ./$PROJNAME-$PROJVER/docs/$PROJNAME*.spec ./tmp.spec
cat tmp.spec|awk -v ver=$PROJVER '{if ($0 ~ /Version:/) print "Version: "ver; else print $0 }' > $PROJNAME-$PROJVER.spec
rm -rf $PROJNAME-$PROJVER
rpmbuild -bb $PROJNAME-$PROJVER.spec
rm tmp.spec
rm $PROJNAME-$PROJVER.spec
rm $PROJNAME-$PROJVER.tar.gz

