.TH stationlist.xml 5 "April 2003" "tvtime 0.9.8"
.SH NAME
stationlist.xml -- tvtime station configuration file

.SH SYNOPSIS

.B ~/.tvtime/stationlist.xml

.SH DESCRIPTION
The stationlist.xml file contains the configuration of channel
information for capture cards with tuners.  It contains a list of active
channels along with their frequencies, renumbering information, and
channel name.

.SH "AUTHORS"
.LP 
Achim Schneider, Billy Biggs

.SH "SEE ALSO"
.BR tvtime (1)
.BR tvtime-command (1)
.BR tvtime.xml (5)
