.TH tvtime.xml 5 "April 2003" "tvtime 0.9.8"
.SH NAME
tvtime.xml -- tvtime configuration file

.SH SYNOPSIS

.B ~/.tvtime/tvtime.xml
.br
.B $PREFIX/etc/tvtime/tvtime.xml
.br

.SH DESCRIPTION
The tvtime.xml file is the main configuration file for tvtime.  It
contains all of the default settings, key bindings, and preset mode
definitions.

.SH "AUTHORS"
.LP 
Billy Biggs

.SH "SEE ALSO"
.BR tvtime (1)
.BR tvtime-command (1)
.BR stationlist.xml (5)
