.TH tvtime-command 1 "April 2003" "tvtime 0.9.8"
.SH NAME
tvtime-command \- control a running tvtime process
.SH SYNOPSIS

\fBtvtime-command\fR [\fICOMMAND\fB\fR] ...

.SH DESCRIPTION
.LP 
tvtime-command allows a user to control a running tvtime process by
sending it commands.  This communicates with tvtime through a fifo.
Commands are case insensitive, and are executed in order.

.SH COMMANDS
.TP
.B AUTO_ADJUST_PICT
Restores the picture settings (brightness, contrast, hue, colour) to
their default values.

.TP
.B BRIGHTNESS_DOWN
Lowers the brightness setting on the input.

.TP
.B BRIGHTNESS_UP
Increases the brightness setting on the input.

.TP
.B CHANNEL_[0-9]
Simulates a keypad number press.

.TP
.B CHANNEL_ACTIVATE_ALL
Re-activates all channels in the list.  Use this to re-initialize the
channel list before running the scanner if you believe some channels are
missing, or if new channels have become available.

.TP
.B CHANNEL_DOWN
Move one channel down in the channel list.

.TP
.B CHANNEL_PREV
Changes to the last channel you were at.  Useful for jumping back and
forth between two programs on distant channels.

.TP
.B CHANNEL_RENUMBER
Renumbers the current channel.  This will swap the current channel with
the number you type in.  Use this to configure your station list to suit
preference or locality.

.TP
.B CHANNEL_SAVE_TUNING
Saves the current fine tuning settings as a custom channel in the
station list.

.TP
.B CHANNEL_SCAN
Walks from the current position through the channel list, disabling any
channels for which no signal is detected.  This command is only
available if signal checking is enabled.

.TP
.B CHANNEL_SKIP
Toggles the current channel as being active or disabled in the station
list.  You can use this to manually scan your channels and enable those
with signal or disable duplicate stations.

.TP
.B CHANNEL_UP
Move one channel up in the channel list.

.TP
.B COLOUR_DOWN / COLOR_DOWN
Decreases the input colour picture setting.  This will make the image
less colourful until it is black-and-white.

.TP
.B COLOUR_UP / COLOR_UP
Increases the input colour picture setting.  This will give the image
more colour.

.TP
.B CONTRAST_DOWN
Decreases the contrast setting of the input.

.TP
.B CONTRAST_UP
Increases the contrast setting of the input.

.TP
.B DISPLAY_INFO
This will re-display the OSD for the current channel, showing the
channel information, current deinterlacer and framerate, the time, and
input settings.

.TP
.B ENTER
Sends a virtual enter command.  Use this when changing the channel, for
example,
.B 'tvtime-command channel_1 channel_5 enter'
will change tvtime to channel 15.

.TP
.B FINETUNE_DOWN
Decreases the fine tuning for the current channel.  Fine tuning can be
saved as a new channel using the
.B CHANNEL_SAVE_TUNING
command.

.TP
.B FINETUNE_UP
Increases the fine tuning for the current channel.

.TP
.B HUE_DOWN
Decreases the hue setting of the input.

.TP
.B HUE_UP
Increases the hue setting of the input.

.TP
.B LUMA_DOWN
Decreases the luma correction value.

.TP
.B LUMA_UP
Increases the luma correction value.

.TP
.B MIXER_DOWN
Decreases the volume setting for the Line In device from /dev/mixer.

.TP
.B MIXER_UP
Increases the volume setting for the Line In device from /dev/mixer.

.TP
.B OVERSCAN_DOWN
Decreases the overscan compensation amount.  This will show more of the
captured input.

.TP
.B OVERSCAN_UP
Increases the overscan compensation amount.  This will show less of the
captured input.

.TP
.B SCREENSHOT
Asks tvtime to take a screenshot.  Screenshots are saved to the
directory listed as the screenshot directory in your configuration file.
The default is the running user's home directory.

.TP
.B SCROLL_CONSOLE_DOWN
Scrolls down in the console's history buffer.

.TP
.B SCROLL_CONSOLE_UP
Scrolls up in the console's history buffer.

.TP
.B SHOW_STATS
This command asks tvtime to output debugging statistics to stderr.

.TP
.B TOGGLE_ASPECT
Toggles the display between 4:3 and 16:9 mode.  Use 16:9 mode if you
have configured an external DVD player or satellite receiver to output
anamorphic 16:9 content.

.TP
.B TOGGLE_AUDIO_MODE
Toggles between the available audio modes on this channel.  It can take
some time before the driver discovers that modes are available.

.TP
.B TOGGLE_BARS
Asks tvtime to display colourbars.  The colourbars are generated by
tvtime and are not related to the capture card, but simply to help
configure your video card and display device.  Once your settings are
correct with these colourbars, try colourbars from an input source like
an external DVD player and make sure they match up.

.TP
.B TOGGLE_CC
Enables closed caption information to be displayed in the tvtime window.
Closed captioning is only available if you have enabled VBI reading in
your
.B tvtime.xml
configuration file.

.TP
.B TOGGLE_CONSOLE
Shows or hides the tvtime console window.  Using the tvtime console, you
can type in any of the commands in this document and have them exeuted.

.TP
.B TOGGLE_DEINTERLACER
This toggles between the available deinterlacing algorithms.

.TP
.B TOGGLE_FULLSCREEN
This toggles between fullscreen and windowed mode.

.TP
.B TOGGLE_FRAMERATE
Toggles the framerate tvtime will output at.  Options are full frame
rate (every field deinterlaced to a frame), half frame rate TFF (every
top field deinterlaced to a frame) and half frame rate BFF (every bottom
field deinterlaced to a frame).

.TP
.B TOGGLE_INPUT
Switches the capture card input used.  Inputs are, for example, the
tuner, composite, or S-Video connectors on the capture card.

.TP
.B TOGGLE_LUMA_CORRECTION
This command enables or disables the luma correction feature in tvtime.
When enabled, this will try to correct for the incorrect colour space
provided by bt848 and bt878 based capture cards.

.TP
.B TOGGLE_MODE
Loads the next saved mode settings.  tvtime's default configuration file
defines two modes: a small window mode with a low quality deinterlacer
setting used, and a high quality large window mode, suitable for use at
fullscreen.

.TP
.B TOGGLE_MUTE
This command will toggle the mute state in the capture card (and not in
your soundcard).

.TP
.B TOGGLE_NTSC_CABLE_MODE
Toggles the NTSC cable mode settings: nominal, IRC, and HRC are
available.

.TP
.B TOGGLE_PAUSE
Enters tvtime's pause mode.  Pause mode is a debugging feature used to
test deinterlacer filters by allowing to see the output of a single set
of frames with various deinterlacers.

.TP
.B TOGGLE_PULLDOWN_DETECTION
Toggles between the available 2-3 pulldown detection modes.  Modes
currently available are vektor's adaptive pulldown detection, and
dalias' pulldown detection.

.TP
.B QUIT
Asks the running tvtime process to exit.

.SH AUTHORS
.LP 
Billy Biggs, Stewart Allen

.SH "SEE ALSO"
.BR tvtime (1)
.BR tvtime.xml (5)
.BR stationlist.xml (5)
