.TH tvtime 1 "February 2003" "tvtime 0.9.7"
.SH "NAME"
.LP 
.B tvtime \- a high quality television application
.SH "SYNTAX"
.LP 
tvtime [\-vamsb] [\-w <width>] [\-I <sampling>] [\-d <device>] [\-i <input>] [\-n <norm>] [\-f <frequencies>] [\-t <tuner>] [\-D <preferred deinterlace method>]
       
.SH "DESCRIPTION"
.LP 
tvtime is a high quality television application for use with video capture cards.  tvtime processes the input from a capture card and displays it on a computer monitor or projector.

  tvtime supports:

.TP
.B o
Deinterlaced output at full interlaced rate of 59.94 frames per second for NTSC
source, or 50 frames per second for PAL sources. This gives smoothness of
motion and high visual quality.

.TP
.B o
Multiple deinterlacing algorithms for finding the optimal mode for the video
content and available processor speed.

.TP
.B o
16:9 aspect ratio mode for the highest available resolution when processing
input from an external DVD player or digital satellite receiver.

.TP
.B o
A super\-slick on\-screen\-display for the complete television experience.
.SH "OPTIONS"
.TP
.B \-h
Show usage information.
.TP
.B \-v
The verbose setting indicates that we should print full informational and
warning messages to stderr while running tvtime.  Otherwise, only fatal errors
will be printed to the output.
.TP
.B \-a
This option starts tvtime in 16:9 aspect ratio mode.
.TP
.B \-s
Print frame skip information (for debugging).
.TP
.B \-m
Start tvtime in fullscreen mode.
.TP
.B -T
V4L input scanline sampling, defaults to 720.
This sets how many pixels per scanline to request from the capture card.
A higher setting gives better quality, while a lower setting means we do
less work, and so tvtime will run faster.  If you have a slower CPU (like,
less than 500Mhz or so), maybe values of 480 or 400 might suit you best.
For best quality, choose a high value like 720 or 768.  Many capture
cards cannot sample higher than 768 pixels per scanline.
.TP
.B \-w
This sets the initial width of the output window, defaults to 800.
.TP
.B \-d
video4linux device to use (defaults to /dev/video0).
.TP
.B \-i
video4linux input number (defaults to 0).  Cards commonly have a bunch of
sources, for example, for my WinTV card source 0 is my tuner and source 1 is
the composite input.
.TP
.B \-c
This turns on luma correction on startup.  Luma correction can be turned on or
off within the application using the 'c' key.
.TP
.B \-l
Luma correction value (defaults to 1.0, use of this implies \-c).  This
indicates the power for correction.  A value of 1.0 does nothing except apply
Bt8x8 correction, if you have a Bt8x8-based capture card.  Values less than one
make the output darker, and values greater than one make the output brighter.
The valid range is 0.1 to 10.0 in increments of 0.1.
.TP
.B \-n
The mode to set the tuner to: PAL, NTSC, SECAM, PAL\-NC, PAL\-M, PAL\-N or
NTSC\-JP (defaults to NTSC).
.TP
.B \-f
The channels you are receiving with the tuner (defaults to us\-cable).

Valid values are:
        us\-cable
        us\-broadcast
        japan\-cable
        japan\-broadcast
        europe
        australia
        france
        russia
.TP
.B \-D
Sets the deinterlace method that will be used when tvtime starts up (defaults to 0).
.SH "FILES"
.LP 
~/.tvtimerc
.SH "AUTHORS"
.LP 
Billy Biggs, Doug Bell, Alexander S. Belov, Achim Schneider,
David I. Lehn, Paul Jara, Robert Högberg, Craig Dooley, Bart Dorsey,
Nicolas Boos, Simon Law, Mark Trolley

.SH "SEE ALSO"
.LP 
tvtimerc(5)
