/**
 * Copyright (c) 1998, 1999, 2000, 2001, 2002, 2003 Billy Biggs and others.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

/**
 * Taglines for tvtime..
 */

static const char *taglines[] = {
"time well wasted",
"it's got more stuff",
"it's what's for dinner",
"now you're playing with power",
"the word of the day",
"a drug-free way to promote regularity",
"taste it again, for the first time",
"a different kind of company, a different kind of tvtime",
"for the strong, silent type",
"it does go well with the chicken",
"the deinterlacer kids ask for by name",
"sweetened with sorbitol",
"mark mcguire's best friend",
"the wholesome snack that smiles back, until you bite its head off",
"because i'm worth it",
"for all your 2000 parts",
"more than meets the eye",
"think different",
"truly outrageous",
"bouncing here and there and everywhere",
"Must See TV",
"we're up to something good",
"is she, or isn't she?",
"it's everywhere you want to be",
"drivers wanted",
"don't leave home without it",
"make room",
"my tv has a first name, it's t-v-t-i-m-e",
"linux: $0, libpng: $0, libsdl: $0, tvtime: priceless",
"Vorsprung durch Technik",
"a tvtime a day helps you work, rest and play",
"I liked the deinterlacer so much... I bought the company",
"top breeders recommend it",
"the best part of waking up",
"smooth like butter",
"those who like it, like it a lot",
"best on the box",
"bringing you what you've always wanted",
"with great power comes great responsibility",
"adult assembly required",
"batteries not included",
"parental guidance suggested",
"can't beat the real thing",
"I Am Canadian",
"now more than ever",
"bud - wis - er",
"a half-hour later in Newfoundland",
"it's not take-out!",
"it's better with the butterfly",
"television without borders",
"1-800-C-A-L-L-A-T-T",
"how do you like your coffee",
"bet you can't eat just one",
"eat great, even late",
"use as directed",
"maybe she's born with it (maybe it's tvtime)",
"viewer discretion is advised",
"oh hungry?",
"an army of one",
"recommended by Dr. Mom",
"sometimes you need a little tvtime, sometimes you need a lot",
"explicit content, parental advisory",
"stays crunchy in milk",
"get your whites whiter than white!",
"the most trusted name in news",
"it's better than bad, it's good",
"the more you use it, the more you love it",
"om katten själv får välja",
"it's finger-licking good",
"have you had your break today?",
"mmmmm, I love tvtime",
"give like Santa, save like Scrooge",
"where do you want to go today?",
"what do you want to watch today?",
"excel-lerate your television",
"dude, you're getting tvtime!",
"got tvtime?",
"we take care",
"quality is job one",
"like a rock",
"can you see the difference?",
"Trusted.  Connected.  Canadian.",
"lita på kraften.",
"how are you?",
"by the power of tvtime, i have the Power!",
"and knowing's half the battle",
"snap, crackle, pop",
"good, good, whole-wheat tvtime",
"when you've got the munchies, nothing else will do",
"zoom zoom",
"watch out for that tree",
"engage",
"sherman, set the Wayback Machine",
"smarter than the average T.V.",
"just slightly ahead of our time",
"solutions for a small planet",
"obey your thirst",
"it's time to play the music, it's time to light the lights",
"i thawt i thaw a telewision.  i did!  i did!",
"overture, curtain, lights!",
"we secretly replaced their coffee with tvtime",
"the revolution will not be televised",
"i can't believe it's not television",
"let's see what in the Tickle Trunk",
"won't you be my neighbour?",
"you call this entertainment?  i'll show you entertainment.",
"did you just whack me with a carrot?",
"how are you going to spend your energy?",
"participaction, keep fit and have fun",
"here i come to save the day",
"you've got questions, we've got answers",
"the other white meat",
"just do it",
"a tvtime is forever",
"takes a licking and keeps on ticking",
"let your fingers do the walking",
"M'm! M'm! Good!",
"be all that you can be",
"when you care enough to send the very best",
"i'd walk a mile for tvtime",
"the pause that refreshes",
"good to the last drop",
"where's the beef?",
"himmelskt gott!",
"you can depend on tvtime",
"tastes great, less filling",
"we're fresh obsessed",
"the best a man can get",
"as seen on TV",
"vad gillar du?",
"is it in you?",
"excite your senses",
"cats ask for it by name",
"give your engine what it wants",
"a sign of good taste",
"so light and fluffy, it won't fill you up",
"the secret's in the taste",
"makes hamburgers taste like steakburgers",
"plop, plop, fizz, fizz, oh what a relief it is!",
"sometimes you feel like a nut. sometimes you don't",
"nobody better lay a finger on my tvtime",
"double your pleasure, double your fun with tvtime, tvtime, tvtime, gum",
"everything you want, nothing you don't",
"the night-time sniffling, sneezing, coughing, aching, stuffy head, fever, so-you-can-rest deinterlacer",
"i don't want to grow up, i'm a tvtime kid",
"extra starka, extra friska",
"grillat är godast",
"i'm lovin' it",
"the most banana of them all"
};

static int numtaglines = ( sizeof( taglines ) / sizeof( char * ) );

