/**
 * Copyright (c) 1998, 1999, 2000, 2001, 2002, 2003 Billy Biggs and others.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

/**
 * Taglines for tvtime..
 */

static const char *taglines[] = {
"tvtime: time well wasted",
"tvtime: it's got more stuff",
"tvtime: it's what's for dinner",
"tvtime: now you're playing with power",
"tvtime: the word of the day",
"tvtime: a drug-free way to promote regularity",
"tvtime: taste it again, for the first time",
"tvtime: a different kind of company, a different kind of tvtime",
"tvtime: for the strong, silent type",
"tvtime: it does go well with the chicken",
"tvtime: the deinterlacer kids ask for by name",
"tvtime: sweetened with sorbitol",
"tvtime: mark mcguire's best friend",
"tvtime: the wholesome snack that smiles back, until you bite its head off",
"tvtime: because i'm worth it",
"tvtime: for all your 2000 parts",
"tvtime: more than meets the eye",
"tvtime: think different",
"tvtime: truly outrageous",
"tvtime: bouncing here and there and everywhere",
"tvtime: Must See TV",
"tvtime: we're up to something good",
"tvtime: is she, or isn't she?",
"tvtime: it's everywhere you want to be",
"tvtime: drivers wanted",
"tvtime: don't leave home without it",
"tvtime: make room",
"tvtime: my tv has a first name, it's t-v-t-i-m-e",
"tvtime: linux: $0, libpng: $0, libsdl: $0, tvtime: priceless",
"tvtime: Vorsprung durch Technik",
"tvtime: a tvtime a day helps you work, rest and play",
"tvtime: I liked the deinterlacer so much... I bought the company",
"tvtime: top breeders recommend it",
"tvtime: the best part of waking up",
"tvtime: smooth like butter",
"tvtime: those who like it, like it a lot",
"tvtime: best on the box",
"tvtime: bringing you what you've always wanted",
"tvtime: with great power comes great responsibility",
"tvtime: adult assembly required",
"tvtime: batteries not included",
"tvtime: parental guidance suggested",
"tvtime: can't beat the real thing",
"tvtime: I Am Canadian",
"tvtime: now more than ever",
"tvtime: bud - wis - er",
"tvtime: a half-hour later in Newfoundland",
"tvtime: it's not take-out!",
"tvtime: it's better with the butterfly",
"tvtime: television without borders",
"tvtime: 1-800-C-A-L-L-A-T-T",
"tvtime: how do you like your coffee",
"tvtime: bet you can't eat just one",
"tvtime: eat great, even late",
"tvtime: use as directed",
"tvtime: maybe she's born with it (maybe it's tvtime)",
"tvtime: viewer discretion is advised",
"tvtime: oh hungry?",
"tvtime: an army of one",
"tvtime: recommended by Dr. Mom",
"tvtime: sometimes you need a little tvtime, sometimes you need a lot",
"tvtime: explicit content, parental advisory",
"tvtime: stays crunchy in milk",
"tvtime: get your whites whiter than white!",
"tvtime: the most trusted name in news",
"tvtime: it's better than bad, it's good",
"tvtime: the more you use it, the more you love it",
"tvtime: om katten själv får välja",
"tvtime: it's finger-licking good",
"tvtime: have you had your break today?",
"tvtime: mmmmm, I love tvtime",
"tvtime; give like Santa, save like Scrooge",
"tvtime: where do you want to go today?",
"tvtime: what do you want to watch today?",
"tvtime: excel-lerate your television",
"tvtime: dude, you're getting tvtime!",
"got tvtime?",
"tvtime: we take care",
"tvtime: quality is job one",
"tvtime: like a rock",
"tvtime: can you see the difference?",
"tvtime: Trusted.  Connected.  Canadian.",
"tvtime: lita på kraften.",
"tvtime: how are you?",
"by the power of tvtime, i have the Power!",
"tvtime: and knowing's half the battle",
"tvtime: snap, crackle, pop",
"tvtime: good, good, whole-wheat tvtime",
"tvtime: when you've got the munchies, nothing else will do",
"tvtime; zoom zoom",
"tvtime: watch out for that tree",
"tvtime: engage",
"tvtime: sherman, set the Wayback Machine",
"tvtime: smarter than the average T.V.",
"tvtime: just slightly ahead of our time",
"tvtime: solutions for a small planet",
"tvtime: obey your thirst",
"tvtime: it's time to play the music, it's time to light the lights",
"tvtime: i thawt i thaw a telewision.  i did!  i did!",
"tvtime: overture, curtain, lights!",
"tvtime: we secretly replaced their coffee with tvtime",
"tvtime: the revolution will not be televised",
"tvtime: i can't believe it's not television",
"tvtime: let's see what in the Tickle Trunk",
"tvtime: won't you be my neighbour?",
"tvtime: you call this entertainment?  i'll show you entertainment.",
"tvtime: did you just whack me with a carrot?",
"tvtime: how are you going to spend your energy?",
"tvtime: participaction, keep fit and have fun",
"tvtime: here i come to save the day",
"tvtime: you've got questions, we've got answers",
"tvtime: the other white meat",
"tvtime: just do it",
"tvtime: a tvtime is forever",
"tvtime: takes a licking and keeps on ticking",
"tvtime: let your fingers do the walking",
"tvtime: M'm! M'm! Good!",
"tvtime: be all that you can be",
"tvtime: when you care enough to send the very best",
"tvtime: i'd walk a mile for tvtime",
"tvtime: the pause that refreshes",
"tvtime: good to the last drop",
"tvtime: where's the beef?",
"tvtime: himmelskt gott!",
"tvtime; you can depend on tvtime",
"tvtime: tastes great, less filling",
"tvtime: we're fresh obsessed",
"tvtime: the best a man can get",
"tvtime: as seen on TV",
"tvtime: vad gillar du?",
"tvtime: is it in you?",
"tvtime: excite your senses",
"tvtime: cats ask for it by name",
"tvtime: give your engine what it wants",
"tvtime: a sign of good taste",
"tvtime: so light and fluffy, it won't fill you up",
"tvtime: the secret's in the taste",
"tvtime: makes hamburgers taste like steakburgers",
"tvtime: plop, plop, fizz, fizz, oh what a relief it is!",
"tvtime: sometimes you feel like a nut. sometimes you don't",
"nobody better lay a finger on my tvtime",
"tvtime: double your pleasure, double your fun with tvtime, tvtime, tvtime, gum",
"tvtime: everything you want, nothing you don't",
"tvtime: the night-time sniffling, sneezing, coughing, aching, stuffy head, fever, so-you-can-rest deinterlacer",
"tvtime: i don't want to grow up, i'm a tvtime kid",
"tvtime: extra starka, extra friska",
"tvtime: grillat är godast",
"tvtime: i'm lovin' it"
};

static int numtaglines = ( sizeof( taglines ) / sizeof( char * ) );

